# Generated by Django 5.0.1 on 2024-02-07 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyschedule',
            name='fifth_lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fifths', to='myapp.subject'),
        ),
        migrations.AlterField(
            model_name='dailyschedule',
            name='first_lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='firsts', to='myapp.subject'),
        ),
        migrations.AlterField(
            model_name='dailyschedule',
            name='fourth_lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fourths', to='myapp.subject'),
        ),
        migrations.AlterField(
            model_name='dailyschedule',
            name='second_lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='seconds', to='myapp.subject'),
        ),
        migrations.AlterField(
            model_name='dailyschedule',
            name='seventh_lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sevenths', to='myapp.subject'),
        ),
        migrations.AlterField(
            model_name='dailyschedule',
            name='sixth_lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sixths', to='myapp.subject'),
        ),
        migrations.AlterField(
            model_name='dailyschedule',
            name='third_lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='thirds', to='myapp.subject'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='schedule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='teacher', to='myapp.weeklyschedule'),
        ),
    ]
